### ISSUE TITLE
ControlNet loading fails

### ISSUE THREAD

**Issue by msartiran** [csslc/CCSR#38]
Hi when I try to run the test script, I get this error while loading controlnet that you have provided.
```
============================
Not !!! use vae encode condition in CONTROLNET
============================
Traceback (most recent call last):
  File "/home/selman/selman_workspace/repos/CCSR/test_ccsr_tile.py", line 255, in <module>
    main(args)
  File "/home/selman/selman_workspace/repos/CCSR/test_ccsr_tile.py", line 128, in main
    pipeline = load_pipeline(args, accelerator, enable_xformers_memory_efficient_attention)
  File "/home/selman/selman_workspace/repos/CCSR/test_ccsr_tile.py", line 55, in load_pipeline
    controlnet = ControlNetModel.from_pretrained(args.controlnet_model_path, subfolder="controlnet")
  File "/home/selman/miniconda3/envs/ccsr/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 646, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'models.controlnet.ControlNetModel'> from preset/models because the following keys are missing: 
 controlnet_cond_embedding.blocks.5.bias, controlnet_cond_embedding.blocks.5.weight, controlnet_cond_embedding.blocks.4.bias, controlnet_cond_embedding.blocks.2.bias, controlnet_cond_embedding.conv_in.weight, controlnet_cond_embedding.blocks.0.bias, controlnet_cond_embedding.blocks.1.bias, controlnet_cond_embedding.blocks.3.weight, controlnet_cond_embedding.conv_out.weight, controlnet_cond_embedding.blocks.1.weight, controlnet_cond_embedding.conv_in.bias, controlnet_cond_embedding.blocks.0.weight, controlnet_cond_embedding.blocks.4.weight, controlnet_cond_embedding.blocks.3.bias, controlnet_cond_embedding.conv_out.bias, controlnet_cond_embedding.blocks.2.weight. 
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
```

**Comment by csslc** [comment]
I reran the code but couldn’t reproduce the error. Could you try re-downloading the ControlNet model to see if the issue might be caused by file corruption? Please ensure the ControlNet model is placed in the `preset/models/controlnet' folder.

**Comment by msartiran** [comment]
yes it is solved. I guess file currupted during download
